/**
 * DRAFT — Roadmap Generation Output Schema
 *
 * This is the structured JSON that `POST /generate/roadmap` will return.
 * Lovable renders each section into the designed slide/PDF layout.
 *
 * Every field is typed so Lovable knows exactly what to display.
 *
 * Each section includes a `section_description` field — this is static
 * boilerplate text that describes the purpose of the section. It is NOT
 * generated by Claude. It is stored as constants in the codebase and
 * injected during the assembly phase. Lovable renders it as-is.
 */

// ─────────────────────────────────────────────
// Section 1: Overview
// ─────────────────────────────────────────────

interface ProcessTimelineStep {
  step: number;
  title: string;
  /** e.g. "Quarterly", "Monthly", or "" if no cadence label */
  cadence: string;
  bullets: string[];
}

interface RoadmapOverview {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  /** "How do we deliver results?" — static 6-step process diagram, injected from boilerplate */
  process_timeline: ProcessTimelineStep[];
  /** Marketing research - injected during assembly, description on the research behind the roadmap */
  research_description: string;
}

// ─────────────────────────────────────────────
// Section 2: Target Market — ICPs + Empathy Maps
// ─────────────────────────────────────────────

interface IdealTargetAccount {
  /** e.g. "Enterprise Event Organizations" */
  name: string;
  /** 30-40 word description */
  description: string;
  location: string;
  industry: string;
  revenue: string;
  number_of_employees: string;
  technologies: string[];
  /** Key characteristics — 3-5 bullet points */
  key_characteristics: string[];
}

interface EmpathyMap {
  fictional_name: string;
  fictional_job_title: string;
  thinks: string;
  feels: string;
  says: string;
  does: string;
  sees: string;
  hears: string;
  pains: string;
  goals: string;
}

interface IdealCustomerProfile {
  target_account: IdealTargetAccount;
  empathy_map: EmpathyMap;
}

interface TargetMarketSection {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  profiles: IdealCustomerProfile[];
}

// ─────────────────────────────────────────────
// Section 3: Brand Positioning & Messaging (StoryBrand)
// ─────────────────────────────────────────────

interface BrandStory {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  character: {
    /** What the customer wants */
    want: string;
  };
  problem: {
    /** The villain — what stands in the way */
    villain: string;
    /** The external problem they face */
    external: string;
    /** The internal problem (how it makes them feel) */
    internal: string;
    /** The philosophical problem (why it matters on a deeper level) */
    philosophical: string;
  };
  guide: {
    /** How the brand demonstrates empathy */
    empathy: string;
    /** How the brand demonstrates authority */
    authority: string;
  };
  plan: {
    /** The process the brand provides */
    process: string;
    /** The agreement or guarantee */
    agreement: string;
  };
  call_to_action: {
    /** Direct CTA */
    direct: string;
    /** Transitional / secondary CTA */
    transitional: string;
  };
  /** 4-5 success factors */
  success: string[];
  /** 2-3 failures the brand helps avoid */
  failure: string[];
  transformation: {
    /** What the customer is BEFORE */
    from: string;
    /** What the customer becomes AFTER */
    to: string;
  };
}

// ─────────────────────────────────────────────
// Section 4: Products & Solutions Matrix
// ─────────────────────────────────────────────

interface ProductsAndSolutions {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  products: ProductSolution[];
}

interface ProductSolution {
  /** Product or solution name */
  product: string;
  /** 50-75 words: what challenges this helps overcome */
  helps_overcome: string;
  /** 50-75 words: the picture of success it provides */
  picture_of_success: string;
  /** 50-75 words: what failure it helps avoid */
  helps_avoid_failure: string;
}

// ─────────────────────────────────────────────
// Section 5: Competition
// ─────────────────────────────────────────────

interface CompetitionSection {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  competitors: CompetitorSnapshot[];
}

interface CompetitorSnapshot {
  company_name: string;
  /** 50-75 word positioning summary */
  positioning_description: string;
  /** Scores from the research document (1-10 scale) */
  scores: {
    organic_seo: number;
    social_media: number;
    content_strategy: number;
    paid_media: number;
    brand_positioning: number;
    overall: number;
  };
  /** 4-5 key observations, 10-15 words each, drawn across all dimensions */
  key_observations: string[];
}

// ─────────────────────────────────────────────
// Section 6: Goals — Annual Goal Alignment
// ─────────────────────────────────────────────

interface AnnualGoal {
  /** The primary business outcome, e.g. "Pipeline Growth" */
  business_outcome: string;
  /** The specific metric, e.g. "Marketing Qualified Leads (MQLs)" */
  metric: string;
  /** How this metric will be tracked and what it represents */
  description: string;
  /** Current baseline from research / meetings */
  benchmark: string;
  /** Specific, measurable annual target */
  annual_goal: string;
  /** Where this data will be tracked/measured */
  data_source: string;
}

interface GoalsSection {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  /** 1-2 key business outcomes (keep it tight) */
  outcomes: AnnualGoal[];
  /** 5 bullet points explaining why these goals are appropriate */
  rationale: string[];
}

// ─────────────────────────────────────────────
// Section 7: Roadmap — 90-Day Phased Execution
// ─────────────────────────────────────────────

interface RoadmapPhase {
  /** e.g. "Month 1: Foundation & Setup" */
  name: string;
  /** e.g. "February 2026" */
  timeframe: string;
  /** The strategic theme for this phase */
  theme: string;
  /** Key deliverables completed in this phase */
  deliverables: string[];
  /** What success looks like at the end of this phase */
  milestone: string;
}

interface RoadmapPhasesSection {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  phases: RoadmapPhase[];
}

// ─────────────────────────────────────────────
// Section 8: Quarterly Marketing Initiatives (OKRs)
// ─────────────────────────────────────────────

interface QuarterlyObjective {
  /** Clear, ambitious goal for the quarter */
  objective: string;
  /** 2-3 specific, measurable key results */
  key_results: string[];
}

interface QuarterlyInitiativesSection {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  objectives: QuarterlyObjective[];
}

// ─────────────────────────────────────────────
// Section 9: Annual High-Level Plan (Gantt-style)
// ─────────────────────────────────────────────

interface AnnualPlanInitiative {
  /** e.g. "Thought Leadership Series" */
  initiative: string;
  /** Brief description of the initiative */
  description: string;
  /**
   * 12-element array, one per month (Jan-Dec or Month 1-12).
   * true = initiative is active that month, false = not active.
   * Lovable renders this as a Gantt bar.
   */
  months: [boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean, boolean];
}

interface AnnualPlanCategory {
  /** e.g. "Content Initiatives", "Demand Generation", "Sales Enablement", "Events", etc. */
  category: string;
  initiatives: AnnualPlanInitiative[];
}

interface AnnualPlan {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  categories: AnnualPlanCategory[];
}

// ─────────────────────────────────────────────
// Section 10: Points Plan
// ─────────────────────────────────────────────

interface PointsPlanTask {
  /** Deliverable name from process library, e.g. "Develop ABM Plan (New Accounts) Document" */
  task: string;
  /** Description from process library */
  description: string;
  /** Stage classification */
  stage: "Foundation" | "Execution" | "Analysis";
  /** Total points for this deliverable */
  points: number;
}

interface MonthlyPointsAllocation {
  /** e.g. "Month 1" or "February 2026" */
  month: string;
  /** Tasks allocated to this month */
  tasks: PointsPlanTask[];
  /** Total points for this month */
  month_total: number;
}

interface PointsPlan {
  /** Static boilerplate — injected during assembly, not generated by Claude */
  section_description: string;
  /** Total points budget for the engagement */
  total_points: number;
  /** Allocation across months (typically 3 months / 90 days) */
  months: MonthlyPointsAllocation[];
}

// ═════════════════════════════════════════════
// FULL OUTPUT SCHEMA
// ═════════════════════════════════════════════

export interface GeneratedRoadmapOutput {
  type: "roadmap";
  title: string;
  /** 1-paragraph executive summary of the entire roadmap */
  summary: string;

  // --- Sections (in presentation order) ---

  overview: RoadmapOverview;
  target_market: TargetMarketSection;
  brand_story: BrandStory;
  products_and_solutions: ProductsAndSolutions;
  competition: CompetitionSection;
  goals: GoalsSection;
  roadmap_phases: RoadmapPhasesSection;
  quarterly_initiatives: QuarterlyInitiativesSection;
  annual_plan: AnnualPlan;
  points_plan: PointsPlan;

  metadata: {
    model: string;
    version: number;
    generated_at: string;
    /** Which research document this roadmap was generated from */
    research_document_title: string;
  };
}

// ═════════════════════════════════════════════
// INPUT SCHEMA (what MiD App sends)
// ═════════════════════════════════════════════

export interface RoadmapGenerationInput {
  client: {
    company_name: string;
    domain: string;
  };

  /** The full research document (output of generate-research) */
  research: {
    /** Full markdown document */
    full_document_markdown: string;
    /** Competitive scores to pass through to competition section */
    competitive_scores: Record<string, {
      organic_seo: number;
      social_media: number;
      content_strategy: number;
      paid_media: number;
      brand_positioning: number;
      overall: number;
    }>;
  };

  /** Meeting transcripts — kickoff, alignment, discovery sessions */
  transcripts: string[];

  /**
   * Process library — the menu of available deliverables.
   * Each entry has a task name, description, stage, and points value.
   * Claude selects from this library and allocates across months.
   */
  process_library: Array<{
    task: string;
    description: string;
    stage: "Foundation" | "Execution" | "Analysis";
    points: number;
  }>;

  /** Total points budget for the engagement */
  points_budget: number;

  /** Strategist-provided instructions (goals, priorities, overrides) */
  instructions?: string;

  /** Custom title override */
  title?: string;
}
